language: python

services:
  - docker

env:
  global:
    - LATEST_TAG=2.4
  matrix:
    - TAG=2.4 HTTPD_VER=2.4.28
    - TAG=2.2 HTTPD_VER=2.2.34

script:
  - make && make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make release TAG="$TAG-$TRAVIS_TAG"
    fi

    if [ "$TAG" == "$LATEST_TAG" ]; then
      make release TAG=latest
    fi
  fi
